homeassistant:
  name: "Frigate Test Home"
  latitude: 40.7128
  longitude: -74.0060
  elevation: 10
  unit_system: metric
  time_zone: UTC
  country: US

frontend:

http:
  ip_ban_enabled: false
  login_attempts_threshold: -1

default_config:

logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug